import type { Metadata } from "next"
import "./globals.css"
import ClientShell from "@/components/ClientShell"
import { ThemeProvider } from "@/context/ThemeProvider"
import { getFooterData } from "@/lib/firestore/getFooterData"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const footerData = await getFooterData()

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var key = "sallify-theme";
                  var stored = localStorage.getItem(key) || "system";
                  var systemDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
                  var theme = stored === "system" ? (systemDark ? "dark" : "light") : stored;
                  document.documentElement.classList.remove("light", "dark");
                  document.documentElement.classList.add(theme);
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body className="antialiased transition-colors duration-300">
        <ThemeProvider>
          <ClientShell footerData={footerData}>{children}</ClientShell>
        </ThemeProvider>
      </body>
    </html>
  )
}
